apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/external-secret.yaml
  - base/default-settings.yaml
  # renovate: datasource=github-releases depName=longhorn/longhorn
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.11.0/deploy/longhorn.yaml
  - base/ingress.yaml

components:
  - ../components/reloader
  - ../components/priority-class-critical

namespace: longhorn-system
