apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate: datasource=github-releases depName=stakater/Reloader
  - https://raw.githubusercontent.com/stakater/Reloader/chart-v2.2.8/deployments/kubernetes/reloader.yaml

namespace: reloader
