apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/secretstore.yaml
  - base/password-generator.yaml

helmCharts:
  # renovate: registryUrl=https://charts.external-secrets.io
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.0.1
    releaseName: "external-secrets"
    namespace: external-secrets
