apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # renovate: datasource=github-releases depName=argoproj/argo-cd
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.2/manifests/install.yaml
  - base/argo-cd-ui-ingress.yaml
  - base/external-secret.yaml
  - base/sync-project.yaml

patches:
  - path: overlays/argocd-cm.yaml
  # - path: overlays/argocd-notifications-cm.yaml
  # - path: overlays/argocd-notifications-controller-deploy.yaml
  # - path: overlays/argocd-rbac-cm.yaml
  # - path: overlays/argocd-server-service.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  # renovate: datasource=github-releases depName=argoproj/argo-cd
  - path: https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.2/notifications_catalog/install.yaml

components:
  - ../components/reloader
  - ../components/priority-class-critical
