apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/external-secret.yaml
  - https://raw.githubusercontent.com/tailscale/tailscale/refs/tags/v1.94.2/cmd/k8s-operator/deploy/manifests/operator.yaml

patches:
  - path: overlays/delete-secret.yaml
  - path: overlays/reload.yaml
    target:
      kind: Deployment

namespace: tailscale
