apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/external-secret.yaml

helmCharts:
  - name: cloudflare-tunnel-ingress-controller
    repo: https://helm.strrl.dev
    # version: 7.3.4
    releaseName: "cloudflare-tunnel-ingress-controller"
    namespace: cloudflare-tunnel-ingress-controller
    valuesFile: values.yaml
