apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/jerichokeyne/argocd-files
    path: cloudflare-ingress
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      refresh: true
    syncOptions:
      - CreateNamespace=true
