apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argo-cd.yaml
  - base/sync.yaml
  - base/reloader.yaml
  - base/cert-manager.yaml
  - base/external-secrets.yaml
  - base/cloudflare-ingress.yaml
  - base/tailscale.yaml
