apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate: datasource=github-releases depName=cert-manager/cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.3/cert-manager.yaml
  - base/external-secret.yaml
  - base/cluster-issuer.yaml

patches:
  - path: overlays/cert-manager-namespace.yaml

components:
  - ../components/priority-class-critical
