apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # TODO: Check https://github.com/cert-manager/cert-manager/releases for new releases
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.3/cert-manager.yaml
  - base/external-secret.yaml
  - base/cluster-issuer.yaml

patches:
  - path: overlays/cert-manager-namespace.yaml
  - path: overlays/patch-priority-class.yaml
    target:
      kind: Deployment
